version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - chmod +x cloudformation/buildspec_postbuild.sh
      - chmod +x bin/provision.sh
      - chmod +x bin/deploy.sh
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - ./cloudformation/buildspec_postbuild.sh