version: 0.2

phases:
  install:
    runtime-versions:
      java: 8
    commands:
      - For testing purpose i didn't gave commands
  build:
    commands:
      - mvn clean install
  post_build:
    commands:
      - ./cloudformation/buildspec_postbuild.sh